services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdamWojs\EzPlatformFormBuilderRecaptcha\FormBuilder\Field\Mapper\ReCaptchaMapper:
        arguments:
            $fieldIdentifier: 'recaptcha'
            $formType: 'AdamWojs\EzPlatformFormBuilderRecaptcha\Form\Type\ReCaptchaFieldType'
        tags:
            - { name: ezplatform.form_builder.field_mapper }
